apiVersion: v1
kind: ConfigMap
metadata:
  name: cgw-configmap
data: 
    config.yaml: |-
        mecID: {{ .Values.cgw.mecID }}
        readTimeout: {{ .Values.cgw.readTimeout }}
        writeTimeout: {{ .Values.cgw.writeTimeout }}
        handlerTimeout: {{ .Values.cgw.handlerTimeout }}
        maxHeaderBytes: {{ .Values.cgw.maxHeaderBytes }}
        port: {{ .Values.cgw.port }}
        upstreamReasonCode: 
            {{- range .Values.cgw.upstreamReasonCode }}
            - {{.}}{{- end }}
        tokenFile: {{ .Values.cgw.caas.tokenFile }}
        caas:
            server: {{ .Values.cgw.caas.server }}
            createEndpoint: {{ .Values.cgw.caas.createEndpoint }}
            deleteEndpoint: {{ .Values.cgw.caas.deleteEndpoint }}
        redis:
            server: {{ .Values.cgw.redis.server }}
            authFile: {{ .Values.cgw.redis.authFile }}
        mqtt:
            server: {{ .Values.cgw.mqtt.server }}
            authType: {{ .Values.cgw.mqtt.authType }}
            successCode: {{ .Values.cgw.mqtt.successCode }}
            authFile: {{ .Values.cgw.mqtt.authFile }}
        debug:
            flushEndpoint: {{ .Values.cgw.debug.flushEndpoint }}
            tokenEndpoint: {{ .Values.cgw.debug.tokenEndpoint }}
            mecEndpoint: {{ .Values.cgw.debug.mecEndpoint }}
            reqLogEndpoint: {{ .Values.cgw.debug.reqLogEndpoint }}
            debugLog: {{ .Values.cgw.debug.debugLog }}