apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: cgw-secrets
data:
    token: {{ .Values.cgw.caas.token | b64enc }}
    mqttAuth: |-
        {{ printf "%s\n%s" .Values.cgw.mqtt.user .Values.cgw.mqtt.password | b64enc }}
    redisAuth: |-
        {{ printf "%s\n%s" .Values.cgw.redis.user .Values.cgw.redis.password | b64enc }}